<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>
    <div class="col2-set pager">
        <div class="col-1">
            <?php if($this->getLastPageNum()>1): ?>
                <?php echo $this->__('%s to %s of %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
            <?php else: ?>
                <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
            <?php endif; ?>
        </div>
        <div class="col-2 page-num a-right">
            <?php echo $this->getPagerHtml() ?>
        </div><div class="clear"></div>
    </div>
<?php endif ?>
