<div class="discount-codes box">
    <form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
    <table align="center">
        <tr>
            <td valign="middle"><h4><?php echo $this->__('Discount Codes') ?></h4></td>
            <td valign="middle">
                <input type="hidden" name="remove" id="remove-coupone" value="0"/>
                <?php if(!strlen($this->getCouponCode())): ?>
                <div><input class="input-text" style="width:70px;" id="coupon_code" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" /></div>
                <?php else: ?>
                <div><input class="input-text" style="width:70px;" id="coupon_code" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" /></div>
                <?php endif;?>
                <div class="clear"></div>
            </td>
            <td valign="middle">
                <?php if(!strlen($this->getCouponCode())): ?>
                    &nbsp;<button class="form-button-alt" onclick="discountForm.submit(false)" type="button" value="<?php echo $this->__('Apply Coupon') ?>"><span><?php echo $this->__('Apply') ?></span></button>
                <?php else: ?>
                    &nbsp;<button class="form-button-alt" onclick="discountForm.submit(false)" type="button"  value="<?php echo $this->__('Apply Coupon') ?>"><span><?php echo $this->__('Apply') ?></span></button>
                    &nbsp;<button class="form-button-alt" type="button" onclick="discountForm.submit(true)" value="<?php echo $this->__('Cancel Coupon') ?>"><span><?php echo $this->__('Cancel') ?></span></button>
                <?php endif;?>
            </td>
        </tr>
        <tr><td colspan="3" align="center"><?php echo $this->__('Enter your coupon code if you have one.') ?></td></tr>
    </table>
</form>
</div>
