<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional/EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body <?php echo $this->getBodyClass()?'class="'.$this->getBodyClass().'"':'' ?>>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
        <div class="middle-container">
            <div class="middle col-2-right-layout">
                <div id="main" class="col-main account-main">
                    <?php echo $this->getChildHtml('global_messages') ?>
                    <?php echo $this->getChildHtml('content') ?>
                </div>
                <div class="col-right side-col account-side">
                    <?php echo $this->getChildHtml('right') ?>
                </div>
            </div>
        </div>
        <div class="header">
            <?php echo $this->getChildHtml('header') ?>
        </div>
        <div class="footer-container">
            <div class="footer">
                <?php echo $this->getChildHtml('footer') ?>
             </div>
        </div>
<?php echo $this->getChildHtml('before_body_end') ?>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
