    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $action ?>" method="post" id="form-validate">
    <fieldset class="group-select">
        <legend><?php echo $this->__('Change Account Password') ?></legend>
        <ul>
            <li>
                <div class="input-box">
                    <label for="current_password"><?php echo $this->__('Current Password') ?> <span class="required">*</span></label><br />
                    <input type="password" class="required-entry input-text" name="current_password" id="current_password" />
                </div>
                        </li>
            <li>
                <div class="input-box">
                    <label for="password"><?php echo $this->__('New Password') ?> <span class="required">*</span></label><br />
                    <input type="password" class="required-entry validate-password input-text" name="password" id="password" />
                </div>
                <div class="input-box">
                    <label for="confirmation"><?php echo $this->__('Confirm New Password') ?> <span class="required">*</span></label><br />
                    <input type="password" class="required-entry validate-cpassword input-text" name="confirmation" id="confirmation" />
                </div>
            </li>
        </ul>
    </fieldset>
    <div class="button-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <a href="<?php echo $this->getUrl('customer/account') ?>" class="float-left">&laquo; <?php echo $this->__('Back') ?></a>
        <input class="form-button" type="submit"><span><?php echo $this->__('Save Password') ?></span></input>
    </div>
    </form>
