<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="page-head-alt button-level">
    <div class="category-head" style="padding-left:5px;"><h2><?php echo $this->__('Shopping Cart') ?></h2></div>
</div>
<?php echo $this->getMessagesBlock()->getGroupedMobileHtml() ?>
<form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
<table cellspacing="0" id="shopping-cart-table" class="data-table box-table shopping-cart">
    <thead>
        <tr>
            <th class="a-center"></th>
            <th class="a-center"><?php echo $this->__('Qty') ?></th>
            <th class="a-center"><?php echo $this->__('Product') ?></th>
            <th class="a-right"><?php echo $this->__('Price') ?><?php echo $this->getIncExcTax(false) ?></th>
            <th class="a-right"><?php echo $this->__('Subtotal') ?><?php echo $this->getIncExcTax(false) ?></th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td colspan="100" class="a-right">
                <button class="form-button-alt" type="submit"><span><?php echo $this->__('Update Cart') ?></span></button>
            </td>
        </tr>
    </tfoot>
    <tbody>
    <?php foreach($this->getItems() as $_item): ?>
        <?php echo $this->getItemHtml($_item) ?>
    <?php endforeach ?>
    </tbody>
</table>
</form>
<div class="shopping-cart-totals">
    <table cellspacing="0" id="shopping-cart-totals-table">
        <tfoot>
        <?php foreach($this->getTotals() as $total): ?>
            <?php if($total->getArea()=='footer'): ?>
            <tr>
                <td><strong><?php echo $total->getTitle() ?></strong></td>
                <td class="nowrap"><strong><?php echo $this->helper('checkout')->formatPrice($total->getValue()) ?></strong></td>
            </tr>
            <?php endif ?>
        <?php endforeach ?>
        </tfoot>
        <tbody>
        <?php foreach($this->getTotals() as $total): ?>
            <?php if(!$total->getArea()): ?>
            <tr>
                <td style="<?php echo $total->getStyle() ?>"><?php echo $total->getTitle() ?></td>
                <td style="<?php echo $total->getStyle() ?>"><?php echo $this->helper('checkout')->formatPrice($total->getValue()) ?></td>
            </tr>
            <?php endif ?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<?php echo $this->getChildHtml('coupon') ?>
<?php if(!$this->hasError()): ?>
<div class="p-methods">
        <?php echo $this->getChildHtml('methods') ?>
</div>
<?php endif; ?>
<?php if($this->getContinueShoppingUrl()): ?>
<p class="a-right" style="padding-right:5px;">
    <a href="<?php echo $this->getContinueShoppingUrl() ?>"><?php echo $this->__('Continue Shopping') ?> &raquo;</a>
</p>
<?php endif; ?>
<br />
