<div class="in-page">
    <div class="page-head">
        <h3><?php echo $this->__('Your order has been received') ?></h3>
    </div>
    <p><strong><?php echo $this->__('Thank you for your purchase!') ?></strong></p>
    <p>
        <?php echo $this->__('Your order # is: %s', $this->getOrderId()) ?>.<br/>
        <?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?><br/>
    </p>
    <div class="button-set">
        <a href="<?php echo $this->getUrl() ?>"><span><?php echo $this->__('Continue Shopping') ?></span></a>
    </div>
</div>
