<?php
/**
 * Temlate for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
?>
<div class="in-page">
    <div class="page-head button-level">
        <div class="col2-set">
            <div class="col-1"><h3><?php echo $this->__('Address Book') ?></h3></div>
            <div class="col-2 a-right"><a href="<?php echo $this->getAddAddressUrl() ?>"><?php echo $this->__('Add New Address') ?></a></div>
            <div class="clear"></div>
        </div><br />
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="col2-set">
        <div class="col-1 primary-address-list">
            <h4><?php echo $this->__('Default Addresses') ?></h4>
            <ol>
            <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
                <li>
                    <h5><?php echo $this->__('Default Billing Address') ?></h5>
                    <address>
                        <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?><br/>
                        <strong><a style="display:block;margin:5px 0;" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Billing Address') ?></a></strong>
                    </address>
                </li>
            <?php elseif($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
                <li>
                    <h5><?php echo $this->__('Default Billing Address') ?></h5>
                    <address>
                        <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?><br/>
                        <strong><a style="display:block;margin:5px 0;" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Billing Address') ?></a></strong>
                    </address>
                </li>
                <?php else: ?>
                <li>
                    <h5><?php echo $this->__('Default Billing Address') ?></h5>
                    <?php echo $this->__('You have no default billing address in your address book.') ?></li>
                <?php endif ?>
                <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
                <li>
                    <h5><?php echo $this->__('Default Shipping Address') ?></h5>
                    <address>
                        <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?><br/>
                        <strong><a style="display:block;margin:5px 0;" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Shipping Address') ?></a></strong>
                    </address>
                </li>
                <?php elseif($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
                <li>
                    <h5><?php echo $this->__('Default Shipping Address') ?></h5><address>
                    <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?><br/>
                    <strong><a style="display:block;margin:5px 0;" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Shipping Address') ?></a></strong>
                    </address>
                </li>
                <?php else: ?>
                <li>
                    <h5><?php echo $this->__('Default Shipping Address') ?></h5><?php echo $this->__('You have no default shipping address in your address book.') ?>
                </li>
                <?php endif ?>
            </ol>
        </div>
        <div class="col-2 address-list">
            <h4><?php echo $this->__('Additional Address Entries') ?></h4>
            <ol>
            <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
                <?php foreach($_pAddsses as $_address): ?>
                <li>
                    <address>
                        <?php echo $this->getAddressHtml($_address) ?><br/>
                        <strong><a href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo $this->__('Edit Address') ?></a></strong>
                        <span class="pipe">|</span>
                        <strong><a href="<?php echo $this->getDeleteUrl()?>id/<?php echo $_address->getId() ?>" class="link-remove"><?php echo $this->__('Delete Address') ?></a></strong>
                    </address>
                </li>
                <?php endforeach; ?>
            <?php else: ?>
                <li><strong><?php echo $this->__('You have no additional address entries in your address book.') ?></strong><br /><br /></li>
            <?php endif ?>
            </ol>
        </div>
    </div><div class="clear"></div>
    <div class="button-set">
        <a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back') ?></a>
    </div><br /><br />
</div>
