<div class="page-head button-level">
    <h3><?php echo $this->__('Compare Products') ?></h3>
</div>
<?php $_total=$this->getItems()->getSize() ?>
<?php if($_total): ?>
<div class="compare-products">
    <table cellspacing="0" class="data-table box-table catalog-listing" id="product_comparison">
<?php if ($_total>2): ?>
        <tbody class="remove-buttons">
            <tr>
                <?php $_i=0 ?>
                <?php foreach($this->getItems() as $_item): ?>
                <?php if($_i++%10==0): ?>
                <td>&nbsp;</td>
                <?php endif; ?>
                <td><a href="<?php echo $this->helper('catalog/product_compare')->getRemoveUrl($_item) ?>"><?php echo $this->__('Remove') ?></a></td>
                <?php endforeach; ?>
            </tr>
        </tbody>
<?php endif ?>
        <tbody>
            <tr class="first">
            <?php $_i=0 ?>
            <?php foreach($this->getItems() as $_item): ?>
                <?php if($_i++%10==0): ?>
                    <td class="label">&nbsp;</td>
                <?php endif; ?>
                <td>
                    <a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a>
                    <h5><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></h5>
                    <?php echo $this->helper('review/product')->getSummaryHtml($_item, 'short') ?>
                    <?php echo $this->helper('catalog/product')->getPriceHtml($_item) ?>
                    <?php if($_item->isSaleable()): ?>
                    <form method="post" action="<?php echo $this->helper('catalog/product_compare')->getAddToCartUrl($_item)?>">
                         <input type="submit" name="submit" class="form-button" value="<?php echo $this->__('Add to Cart') ?>"/><br/>
                    </form>
                    <?php else: ?>
                    <div class="out-of-stock"><?php echo $this->__('Out of stock') ?></div>
                    <?php endif; ?>
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <a href="<?php echo $this->helper('catalog/product_compare')->getAddToWishlistUrl($_item) ?>"><small><?php echo $this->__('Add to Wishlist') ?></small></a>
                    <?php endif; ?>
                </td>
            <?php endforeach; ?>
            </tr>
        </tbody>
        <tbody>
        <?php foreach ($this->getAttributes() as $_attribute): ?>
            <tr>
                <?php $_i=0 ?>
                <?php foreach($this->getItems() as $_item): ?>
                <?php if($_i++%10==0): ?>
                <td class="label"><?php echo $_attribute->getFrontendLabel() ?></td>
                <?php endif; ?>
                <td>
                    <?php switch ($_attribute->getAttributeCode()) {
                        case "price": ?>
                            <?php echo $this->helper('catalog/product')->getPriceHtml($_item) ?>
                            <?php break;
                        case "small_image": ?>
                            <img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(125, 125); ?>" width="125" height="125" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" />
                            <?php break;
                        default: ?>
                            <?php echo nl2br($this->getProductAttributeValue($_item, $_attribute)) ?>
                            <?php break;
                    } ?>
                </td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
        <tbody class="attribute-cart">
                <tr>
                <?php $_i=0 ?>
                <?php foreach($this->getItems() as $_item): ?>
                <?php if($_i++%10==0): ?>
                 <td class="label">&nbsp;</td>
                <?php endif; ?>
                <td>
                    <?php echo $this->helper('catalog/product')->getPriceHtml($_item) ?>
                    <?php if($_item->isSaleable()): ?>
                    <form method="post" action="<?php echo $this->helper('catalog/product_compare')->getAddToCartUrl($_item) ?>">
                    <input type="submit" class="form-button" value="<?php echo $this->__('Add to Cart') ?>" name="submit"/><br/>
                    </form>
                    <?php else: ?>
                    <div class="out-of-stock"><?php echo $this->__('Out of stock') ?></div>
                    <?php endif; ?>
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <a href="<?php echo $this->helper('catalog/product_compare')->getAddToWishlistUrl($_item) ?>"><small><?php echo $this->__('Add to Wishlist') ?></small></a>
                    <?php endif; ?>
                </td>
                <?php endforeach; ?>
            </tr>
        </tbody>
    </table>
</div>
<?php endif; ?>
