<?php 
/**
 * Top menu for store
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>
<div class="header-nav-container">
    <div><?php echo $this->__('Category')?></div>
    <div class="header-nav">
        <?php $count = $this->getStoreCategories()->count(); ?>
        <?php foreach ($this->getStoreCategories() as $_category): ?>
            <?php $count--;?>
            <?php if($count != 0): ?>
                <?php echo $this->drawItemSingle($_category, 0, true) ?>
            <?php else: ?>
                <?php echo $this->drawItemSingle($_category, 0, false) ?>
            <?php endif ?>        
        <?php endforeach ?>
    </div>
</div>
