<?php
/**
 * @see Mage_Page_Block_Template_Links
 */
?>
<?php $_links = $this->getLinks(); ?>
<?php if(count($_links)>0): ?>
    <div>
    <?php echo $this->getName() ?><br/>
            <?php foreach($_links as $_link): ?>
                <?php if($_link->getIsLast()): ?>┗<?php else: ?>┣<?php endif; ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?><?php echo $_link->getAfterText() ?></a><br/>
            <?php endforeach; ?>
   </div>
<?php endif; ?>
