<div class="in-page">
    <div class="page-head"><h3><?php echo $this->__('My Dashboard') ?></h3></div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('hello') ?>
    <?php echo $this->getChildHtml('top') ?>
    <div class="account-box ad-account-info">
        <div class="page-head"><h3><?php echo $this->__('Account Information') ?></h3></div>
        <?php echo $this->getChildHtml('info') ?>
        <?php echo $this->getChildHtml('address') ?>
    </div>
</div><div class="clear"></div><br />
