<h2>Address Book</h2>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<table cellspacing="0" width="100%">
    <tr>
        <td style="width:50%;"><h3>Primary</h3>
            <table width="100%" cellspacing="0"> 
            <?php if(!empty($primaryAddresses)): ?>    
                <?php foreach($primaryAddresses as $_address): ?>
                <tr>
                    <td>
                    <address>
                        <?php echo nl2br($_address->toString("{{lastname}} {{firstname}}\n{{postcode}}\n{{regionName}}{{city}}{{street}}\nT: {{telephone}}")) ?>
                    </address>
                    <p>
                        <strong><a href="<?php echo $this->getUrl('customer/address/form', array('address'=>$_address->getAddressId())) ?>" class="red-link"><?php echo $this->__('Edit Address') ?></a></strong>
                    </p>
                    </td>
                </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td>
                        <p><?php echo $this->__('You have no primary entries in your address book.') ?></p>
                    </td>
                </tr>
            <?php endif ?>
            </table>
        </td>
        <td style="width:50%;"><h3><?php echo $this->__('Additional Address Entries') ?></h3>
            <table width="100%" cellspacing="0"> 
            <?php if(!empty($alternativeAddresses)): ?>    
                <?php foreach($alternativeAddresses as $_address): ?>
                <tr>
                    <td>
                    <address>
                        <?php echo nl2br($_address->toString("{{lastname}} {{firstname}}\n{{postcode}}\n{{regionName}}{{city}}{{street}}\nT: {{telephone}}")) ?>
                    </address>
                    <p>
                        <strong><a href="<?php echo $this->getUrl('customer/address/form', array('address'=>$_address->getAddressId())) ?>" class="red-link"><?php echo $this->__('Edit Address') ?></a></strong><span class="separator">&nbsp;|&nbsp;</span><strong><a href="<?php echo $this->getUrl("customer/address/delete")?>address/<?php echo $_address->getAddressId() ?>" class="red-link"><?php echo $this->__('Delete Address') ?></a></strong>
                    </p>
                    </td>
                </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td>
                        <p><?php echo $this->__('You have no additional entries in your address book.') ?></p>
                    </td>
                </tr>
            <?php endif ?>
            </table>
        </td>
    </tr>
</table>
<div class="buttons-container">
    <a href="<?php echo $this->getUrl('customer/account/') ?>" class="float-left">&laquo; <?php echo $this->__('Back') ?></a>
    <a href="<?php echo $this->getUrl('customer/address/form') ?>"><?php echo $this->__('New Address') ?></a>
</div>
