    <div class="page-head">
            <h3><?php echo $this->__('My Orders') ?></h3>
        </div>

<?php if($orders->getSize()): ?>
    <table cellspacing="0" width="100%" class="data-table" id="my-orders-table" >
        <thead>
            <tr>
                <th><?php echo $this->__('Order #') ?></th>
                <th><?php echo $this->__('Date') ?></th>
                <!--<th class="align-center">Shipped To</th>-->
                <th class="a-right"><?php echo $this->__('Total') ?></th>
                <th class="a-center"><?php echo $this->__('Status') ?></th>
                <th ><?php echo $this->__('Details') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($orders as $order): ?>
            <tr>
                <td><?php echo $order->getRealOrderId() ?>&nbsp;</td>
                <td><?php echo date("Y/M/D", strtotime($order->getCreatedAt())) ?>&nbsp;</td>
                <!--<td class="align-center">{$page.orders[io].customer}</td>-->
                <td class="a-right"><?php echo $order->getGrandTotal() ?>&nbsp;</td>
                <td class="a-center"><?php echo $order->getStatus() ?>&nbsp;</td>
                <td><a href="<?php echo $this->getUrl('customer/order/view', array('order'=>$order->getOrderId())) ?>"><?php echo $this->__('View Order') ?></a>&nbsp;</td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders yet.') ?></p>
<?php endif ?>
<div class="buttons-container">
    <a href="<?php echo $this->getUrl('customer/account') ?>" class="float-left">&laquo; <?php echo $this->__('Back') ?></a>
</div>
