<?php $_product = $this->getProduct() ?>

<?php if($_product->isSaleable()): ?>
        <?php if(!$_product->isGrouped()): ?>
        <span class="qty-box"><label for="qty"><?php echo $this->__('Qty') ?>:</label>
        <select name="qty" class="input-text qty" id="qty">
            <?php $minQty = 1; 
                  if($this->getMinimalQty($_product) > $minQty):
                      $minQty = $this->getMinimalQty($_product);
                  endif;
            ?>
            <?php for($i=$minQty; $i<=10; $i++):?>
            <option value="<?php echo $i ?>"><?php echo $i ?></option>
            <?php endfor;?>
        <?php endif; ?>
        </select>
        <br/>
        <input type="submit" class="form-button" value="<?php echo $this->__('Add to Cart') ?>" />
<?php endif; ?>
