<div>
    <div>
        <div class="col-2">
            <div class="user-links">
                <div class="shop-access">
                    <?php echo $this->getChildHtml('topLinks') ?>
                </div><div class="clear"></div>

                <?php if($toplinks && is_array($toplinks)): ?>
                <ul>
                    <?php echo $this->getChildHtml() ?>
                    <?php foreach($toplinks as $_toplink): ?>
                    <li<?php if($_toplink['first']||$_toplink['last']): ?> class="<?php if($_toplink['first']): ?>first <?php endif; ?><?php if($_toplink['last']): ?>last <?php endif; ?>"<?php endif; ?> <?php echo $_toplink['liParams'] ?>>        <?php echo $_toplink['beforeText'] ?><a <?php echo $_toplink['aParams'] ?>><?php echo $_toplink['innerText'] ?></a><?php echo $_toplink['afterText'] ?></li>
                    <?php endforeach; ?>
                </ul>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
