<div>
    <div>
        <div class="col-2">
            <div class="user-links">
                <div class="shop-access">
                <?php if($toplinks && is_array($toplinks)): ?>
                    <?php echo $this->getChildHtml() ?>
                    <?php foreach($toplinks as $_toplink): ?>
                    <?php if($_toplink['last']): ?>┗<?php else:?>┣<?php endif; ?><?php endif; ?> <?php echo $_toplink['liParams'] ?>>        <?php echo $_toplink['beforeText'] ?><a <?php echo $_toplink['aParams'] ?>><?php echo $_toplink['innerText'] ?></a><?php echo $_toplink['afterText'] ?>
                    <?php endforeach; ?>
                <?php endif; ?>
                </div><div class="clear"></div>
            </div>
        </div>
    </div>
</div>
