<div class="dashboard-block">
    <div class="inner-head">
        <h5><?php echo $this->__('Address Book') ?></h5>
        <a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a>
        <div class="clear"></div>
    </div>
    <div><br />
        <div style="margin:8px 5px;">
            <h6><?php echo $this->__('Primary Billing Address') ?></h6>
            <address>
                <?php echo $this->getPrimaryBillingAddressHtml() ?><br />
                <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
            </address>
        </div>
        <div style="margin:8px 5px;">
            <h6><?php echo $this->__('Primary Shipping Address') ?></h6>
            <address>
                <?php echo $this->getPrimaryShippingAddressHtml() ?><br />
                <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
            </address>
        </div>
    </div>
</div>
