<div>
    <div class="dashboard-block">
        <div class="inner-head">
            <h5><?php echo $this->__('Contact Information') ?></h5>
            <a href="<?php echo $this->getUrl('customer/account/edit') ?>"><?php echo $this->__('Edit') ?></a>
            <div class="clear"></div>
        </div>
        <p style="line-height:14px;">
            <?php echo $this->htmlEscape($this->getCustomer()->getFirstname()) ?>
            <?php echo $this->htmlEscape($this->getCustomer()->getLastname()) ?><br />
            <?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?><br />
            <a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change Password') ?></a>
        </p>
    </div>
    <?php if( $this->isNewsletterEnabled() ): ?>
    <div class="dashboard-block">
        <div class="inner-head">
            <h5><?php echo $this->__('Newsletters') ?></h5>
            <a href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Edit') ?></a>
            <div class="clear"></div>
        </div>
        <p>
            <?php if( $this->getIsSubscribed() ): ?>
                <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
            <?php else: ?>
                <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
            <?php endif; ?>
        </p>
    </div>
    <?php endif; ?>
</div><div class="clear"></div>
<br />
